id: I3E289D4E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:25:36+00:00'
last_modified: '2022-06-07T12:35:13.979359+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD76232
  title: ཆོས་རྗེ་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དད་པའི་གསོས་སྨན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7B39:
      image_group_id: I1PD76235
      title: ''
      total_pages: 98
      order: 1
      base_file: 7B39.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
